-- Raises the sport_write_context budget ceiling to 8589934592 bytes (8 GiB).
-- Application allocation, NOT a spending cap; D1 allows up to 10 GB per database on the paid plan.
-- Generated by scripts/generar-guardia-deportiva.ts; verify with --comprobar.
-- Rebuilds only sport_write_context, sport_write_authorized and the sport_context_* triggers.
-- sport_capacity_ledger and every other guard are untouched. Fails (CHECK constraint)
-- and rolls back unless no write context or charge is open.
CREATE TABLE _guardia_0005 (abiertos INTEGER NOT NULL CHECK (abiertos = 0));
INSERT INTO _guardia_0005(abiertos) SELECT (SELECT count(*) FROM sport_write_context)+(SELECT count(*) FROM sport_write_charge);
DROP TABLE _guardia_0005;
DROP VIEW sport_write_authorized;
DROP TABLE sport_write_context;
CREATE TABLE sport_write_context (
    key TEXT PRIMARY KEY CHECK (key = 'global'), owner TEXT NOT NULL,
    lease_version INTEGER NOT NULL CHECK (lease_version > 0),
    budget_bytes INTEGER NOT NULL CHECK (
      typeof(budget_bytes)='integer' AND budget_bytes>0 AND budget_bytes<=8589934592),
    projected_bytes INTEGER NOT NULL CHECK (
      typeof(projected_bytes)='integer' AND projected_bytes>=16384),
    measured_bytes INTEGER NOT NULL CHECK (
      typeof(measured_bytes)='integer' AND measured_bytes>0));
CREATE VIEW sport_write_authorized AS
    SELECT 1 AS ok FROM sport_write_context c JOIN sport_write_lease l
      ON l.key=c.key AND l.owner=c.owner AND l.lease_version=c.lease_version
    JOIN sport_capacity_ledger b ON b.key=c.key
    WHERE l.key='global' AND l.expires_at >
      (cast(strftime('%s','now') as integer)*1000 + cast(substr(strftime('%f','now'),4,3) as integer))
      AND b.blocked=0 AND b.accounted_bytes<c.budget_bytes;
CREATE TRIGGER sport_context_claim BEFORE INSERT ON sport_write_context BEGIN
    SELECT CASE WHEN EXISTS (SELECT 1 FROM sport_write_context)
      OR EXISTS (SELECT 1 FROM sport_write_charge) OR NOT EXISTS (
        SELECT 1 FROM sport_write_lease l WHERE l.key=NEW.key AND l.owner=NEW.owner
          AND l.lease_version=NEW.lease_version AND l.expires_at >
          (cast(strftime('%s','now') as integer)*1000 + cast(substr(strftime('%f','now'),4,3) as integer))
      ) THEN RAISE(ABORT, 'sport_write_lease_required') END;
    SELECT CASE WHEN NOT EXISTS (
      SELECT 1 FROM sport_capacity_ledger b WHERE b.key=NEW.key AND b.blocked=0
        AND max(b.accounted_bytes,NEW.measured_bytes)+NEW.projected_bytes<NEW.budget_bytes
      ) THEN RAISE(ABORT, 'sport_capacity') END;
    END;
CREATE TRIGGER sport_context_reserve AFTER INSERT ON sport_write_context BEGIN
    INSERT INTO sport_write_charge(key,remaining_bytes)
      VALUES(NEW.key,NEW.projected_bytes-16384);
    UPDATE sport_capacity_ledger
      SET accounted_bytes=max(accounted_bytes,NEW.measured_bytes)+16384 WHERE key=NEW.key;
    END;
CREATE TRIGGER sport_context_close BEFORE DELETE ON sport_write_context BEGIN
    SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM sport_write_authorized)
      OR NOT EXISTS (SELECT 1 FROM sport_write_charge WHERE key=OLD.key)
      THEN RAISE(ABORT, 'sport_write_lease_or_capacity_lost') END;
    DELETE FROM sport_write_charge WHERE key=OLD.key;
    END;
CREATE TRIGGER sport_context_immutable BEFORE UPDATE ON sport_write_context BEGIN
    SELECT RAISE(ABORT, 'sport_write_context_immutable'); END;
