-- Relays of team competitions (relevos): one row per team match and one per relay, as Engarde
-- publishes them (the FIE does not publish relays). Built offline by scripts/relevos.ts from
-- calendario-trabajo/relevos/<source>/*.json.
-- Additive only: two new tables that the deployed code never reads. Apply BEFORE loading the
-- SQL that scripts/relevos.ts generates, and apply it to the local base.sqlite too so it stays an
-- exact copy of production.
--
-- sport_team_match: one team match of a team competition (sport_competition.format = 'EQUIPOS').
--   source_key: the source anchor of the match (Engarde `a8-1`); round_key as in sport_bout
--   (`T8`, `T2-3`…), NULL for placement tables; team_*_ref: source_fact_key of the team placing in
--   sport_result when the published name matched it, else NULL. consistent = every relay adds up
--   and the last one ends in the final score.
-- sport_relay: one relay of a match. fencer_*_person_id is set only when the fencer was matched
--   to a person inside that competition (team members, or individual results of the same
--   tournament, weapon and gender from the same club or country); never by name across the base.
--   touches_* are the hits of each fencer in that relay; before_*/after_* the cumulative score.
--   Relays never count as bouts (sport_bout) and never enter the rival counts.
-- Same write guard as the other sport_* tables (0002): lease + capacity charge per row.
CREATE TABLE sport_team_match (
  id TEXT PRIMARY KEY NOT NULL,
  competition_id TEXT NOT NULL REFERENCES sport_competition(id) ON DELETE CASCADE,
  source TEXT NOT NULL,
  source_key TEXT NOT NULL CHECK (length(source_key) BETWEEN 1 AND 40),
  phase TEXT NOT NULL CHECK (phase IN ('POULE', 'TABLEAU')),
  round_key TEXT,
  round_label TEXT,
  team_a_name TEXT NOT NULL,
  team_b_name TEXT NOT NULL,
  team_a_ref TEXT,
  team_b_ref TEXT,
  score_a INTEGER NOT NULL CHECK (typeof(score_a) = 'integer' AND score_a BETWEEN 0 AND 999),
  score_b INTEGER NOT NULL CHECK (typeof(score_b) = 'integer' AND score_b BETWEEN 0 AND 999),
  consistent INTEGER NOT NULL CHECK (consistent IN (0, 1)),
  source_url TEXT
);
CREATE UNIQUE INDEX sport_team_match_key ON sport_team_match (competition_id, source, source_key);
CREATE TABLE sport_relay (
  id TEXT PRIMARY KEY NOT NULL,
  match_id TEXT NOT NULL REFERENCES sport_team_match(id) ON DELETE CASCADE,
  relay_number INTEGER NOT NULL CHECK (typeof(relay_number) = 'integer' AND relay_number BETWEEN 1 AND 99),
  fencer_a_name TEXT,
  fencer_b_name TEXT,
  fencer_a_person_id TEXT REFERENCES sport_person(id) ON DELETE SET NULL,
  fencer_b_person_id TEXT REFERENCES sport_person(id) ON DELETE SET NULL,
  touches_a INTEGER NOT NULL CHECK (typeof(touches_a) = 'integer' AND touches_a BETWEEN 0 AND 999),
  touches_b INTEGER NOT NULL CHECK (typeof(touches_b) = 'integer' AND touches_b BETWEEN 0 AND 999),
  before_a INTEGER NOT NULL CHECK (typeof(before_a) = 'integer' AND before_a BETWEEN 0 AND 999),
  before_b INTEGER NOT NULL CHECK (typeof(before_b) = 'integer' AND before_b BETWEEN 0 AND 999),
  after_a INTEGER NOT NULL CHECK (typeof(after_a) = 'integer' AND after_a BETWEEN 0 AND 999),
  after_b INTEGER NOT NULL CHECK (typeof(after_b) = 'integer' AND after_b BETWEEN 0 AND 999),
  consistent INTEGER NOT NULL CHECK (consistent IN (0, 1)),
  CHECK (fencer_a_person_id IS NULL OR fencer_b_person_id IS NULL OR fencer_a_person_id <> fencer_b_person_id)
);
CREATE UNIQUE INDEX sport_relay_key ON sport_relay (match_id, relay_number);
-- By person (either side) and by pair of people, like sport_bout_a_idx / sport_bout_b_idx.
CREATE INDEX sport_relay_a_idx ON sport_relay (fencer_a_person_id, fencer_b_person_id) WHERE fencer_a_person_id IS NOT NULL;
CREATE INDEX sport_relay_b_idx ON sport_relay (fencer_b_person_id, fencer_a_person_id) WHERE fencer_b_person_id IS NOT NULL;
CREATE TRIGGER sport_fence_sport_team_match_insert BEFORE INSERT ON sport_team_match BEGIN SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM sport_write_authorized) THEN RAISE(ABORT, 'sport_write_lease_required') END; END;
CREATE TRIGGER sport_fence_sport_team_match_update BEFORE UPDATE ON sport_team_match BEGIN SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM sport_write_authorized) THEN RAISE(ABORT, 'sport_write_lease_required') END; END;
CREATE TRIGGER sport_fence_sport_team_match_delete BEFORE DELETE ON sport_team_match BEGIN SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM sport_write_authorized) THEN RAISE(ABORT, 'sport_write_lease_required') END; END;
CREATE TRIGGER sport_charge_sport_team_match_insert AFTER INSERT ON sport_team_match BEGIN
    SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM sport_write_authorized) OR NOT EXISTS (
      SELECT 1 FROM sport_write_charge WHERE key='global' AND remaining_bytes>=1024+4*(coalesce(length(CAST(NEW."id" AS BLOB)),0)+coalesce(length(CAST(NEW."competition_id" AS BLOB)),0)+coalesce(length(CAST(NEW."source" AS BLOB)),0)+coalesce(length(CAST(NEW."source_key" AS BLOB)),0)+coalesce(length(CAST(NEW."phase" AS BLOB)),0)+coalesce(length(CAST(NEW."round_key" AS BLOB)),0)+coalesce(length(CAST(NEW."round_label" AS BLOB)),0)+coalesce(length(CAST(NEW."team_a_name" AS BLOB)),0)+coalesce(length(CAST(NEW."team_b_name" AS BLOB)),0)+coalesce(length(CAST(NEW."team_a_ref" AS BLOB)),0)+coalesce(length(CAST(NEW."team_b_ref" AS BLOB)),0)+coalesce(length(CAST(NEW."score_a" AS BLOB)),0)+coalesce(length(CAST(NEW."score_b" AS BLOB)),0)+coalesce(length(CAST(NEW."consistent" AS BLOB)),0)+coalesce(length(CAST(NEW."source_url" AS BLOB)),0))
    ) THEN RAISE(ABORT, 'sport_capacity_reservation_exhausted') END;
    UPDATE sport_write_charge SET remaining_bytes=remaining_bytes-(1024+4*(coalesce(length(CAST(NEW."id" AS BLOB)),0)+coalesce(length(CAST(NEW."competition_id" AS BLOB)),0)+coalesce(length(CAST(NEW."source" AS BLOB)),0)+coalesce(length(CAST(NEW."source_key" AS BLOB)),0)+coalesce(length(CAST(NEW."phase" AS BLOB)),0)+coalesce(length(CAST(NEW."round_key" AS BLOB)),0)+coalesce(length(CAST(NEW."round_label" AS BLOB)),0)+coalesce(length(CAST(NEW."team_a_name" AS BLOB)),0)+coalesce(length(CAST(NEW."team_b_name" AS BLOB)),0)+coalesce(length(CAST(NEW."team_a_ref" AS BLOB)),0)+coalesce(length(CAST(NEW."team_b_ref" AS BLOB)),0)+coalesce(length(CAST(NEW."score_a" AS BLOB)),0)+coalesce(length(CAST(NEW."score_b" AS BLOB)),0)+coalesce(length(CAST(NEW."consistent" AS BLOB)),0)+coalesce(length(CAST(NEW."source_url" AS BLOB)),0))) WHERE key='global';
    UPDATE sport_capacity_ledger SET accounted_bytes=accounted_bytes+(1024+4*(coalesce(length(CAST(NEW."id" AS BLOB)),0)+coalesce(length(CAST(NEW."competition_id" AS BLOB)),0)+coalesce(length(CAST(NEW."source" AS BLOB)),0)+coalesce(length(CAST(NEW."source_key" AS BLOB)),0)+coalesce(length(CAST(NEW."phase" AS BLOB)),0)+coalesce(length(CAST(NEW."round_key" AS BLOB)),0)+coalesce(length(CAST(NEW."round_label" AS BLOB)),0)+coalesce(length(CAST(NEW."team_a_name" AS BLOB)),0)+coalesce(length(CAST(NEW."team_b_name" AS BLOB)),0)+coalesce(length(CAST(NEW."team_a_ref" AS BLOB)),0)+coalesce(length(CAST(NEW."team_b_ref" AS BLOB)),0)+coalesce(length(CAST(NEW."score_a" AS BLOB)),0)+coalesce(length(CAST(NEW."score_b" AS BLOB)),0)+coalesce(length(CAST(NEW."consistent" AS BLOB)),0)+coalesce(length(CAST(NEW."source_url" AS BLOB)),0))) WHERE key='global';
    END;
CREATE TRIGGER sport_charge_sport_team_match_update AFTER UPDATE ON sport_team_match BEGIN
    SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM sport_write_authorized) OR NOT EXISTS (
      SELECT 1 FROM sport_write_charge WHERE key='global' AND remaining_bytes>=1024+4*(CASE WHEN NEW."id" IS OLD."id" THEN 0 ELSE coalesce(length(CAST(NEW."id" AS BLOB)),0) END+CASE WHEN NEW."competition_id" IS OLD."competition_id" THEN 0 ELSE coalesce(length(CAST(NEW."competition_id" AS BLOB)),0) END+CASE WHEN NEW."source" IS OLD."source" THEN 0 ELSE coalesce(length(CAST(NEW."source" AS BLOB)),0) END+CASE WHEN NEW."source_key" IS OLD."source_key" THEN 0 ELSE coalesce(length(CAST(NEW."source_key" AS BLOB)),0) END+CASE WHEN NEW."phase" IS OLD."phase" THEN 0 ELSE coalesce(length(CAST(NEW."phase" AS BLOB)),0) END+CASE WHEN NEW."round_key" IS OLD."round_key" THEN 0 ELSE coalesce(length(CAST(NEW."round_key" AS BLOB)),0) END+CASE WHEN NEW."round_label" IS OLD."round_label" THEN 0 ELSE coalesce(length(CAST(NEW."round_label" AS BLOB)),0) END+CASE WHEN NEW."team_a_name" IS OLD."team_a_name" THEN 0 ELSE coalesce(length(CAST(NEW."team_a_name" AS BLOB)),0) END+CASE WHEN NEW."team_b_name" IS OLD."team_b_name" THEN 0 ELSE coalesce(length(CAST(NEW."team_b_name" AS BLOB)),0) END+CASE WHEN NEW."team_a_ref" IS OLD."team_a_ref" THEN 0 ELSE coalesce(length(CAST(NEW."team_a_ref" AS BLOB)),0) END+CASE WHEN NEW."team_b_ref" IS OLD."team_b_ref" THEN 0 ELSE coalesce(length(CAST(NEW."team_b_ref" AS BLOB)),0) END+CASE WHEN NEW."score_a" IS OLD."score_a" THEN 0 ELSE coalesce(length(CAST(NEW."score_a" AS BLOB)),0) END+CASE WHEN NEW."score_b" IS OLD."score_b" THEN 0 ELSE coalesce(length(CAST(NEW."score_b" AS BLOB)),0) END+CASE WHEN NEW."consistent" IS OLD."consistent" THEN 0 ELSE coalesce(length(CAST(NEW."consistent" AS BLOB)),0) END+CASE WHEN NEW."source_url" IS OLD."source_url" THEN 0 ELSE coalesce(length(CAST(NEW."source_url" AS BLOB)),0) END)
    ) THEN RAISE(ABORT, 'sport_capacity_reservation_exhausted') END;
    UPDATE sport_write_charge SET remaining_bytes=remaining_bytes-(1024+4*(CASE WHEN NEW."id" IS OLD."id" THEN 0 ELSE coalesce(length(CAST(NEW."id" AS BLOB)),0) END+CASE WHEN NEW."competition_id" IS OLD."competition_id" THEN 0 ELSE coalesce(length(CAST(NEW."competition_id" AS BLOB)),0) END+CASE WHEN NEW."source" IS OLD."source" THEN 0 ELSE coalesce(length(CAST(NEW."source" AS BLOB)),0) END+CASE WHEN NEW."source_key" IS OLD."source_key" THEN 0 ELSE coalesce(length(CAST(NEW."source_key" AS BLOB)),0) END+CASE WHEN NEW."phase" IS OLD."phase" THEN 0 ELSE coalesce(length(CAST(NEW."phase" AS BLOB)),0) END+CASE WHEN NEW."round_key" IS OLD."round_key" THEN 0 ELSE coalesce(length(CAST(NEW."round_key" AS BLOB)),0) END+CASE WHEN NEW."round_label" IS OLD."round_label" THEN 0 ELSE coalesce(length(CAST(NEW."round_label" AS BLOB)),0) END+CASE WHEN NEW."team_a_name" IS OLD."team_a_name" THEN 0 ELSE coalesce(length(CAST(NEW."team_a_name" AS BLOB)),0) END+CASE WHEN NEW."team_b_name" IS OLD."team_b_name" THEN 0 ELSE coalesce(length(CAST(NEW."team_b_name" AS BLOB)),0) END+CASE WHEN NEW."team_a_ref" IS OLD."team_a_ref" THEN 0 ELSE coalesce(length(CAST(NEW."team_a_ref" AS BLOB)),0) END+CASE WHEN NEW."team_b_ref" IS OLD."team_b_ref" THEN 0 ELSE coalesce(length(CAST(NEW."team_b_ref" AS BLOB)),0) END+CASE WHEN NEW."score_a" IS OLD."score_a" THEN 0 ELSE coalesce(length(CAST(NEW."score_a" AS BLOB)),0) END+CASE WHEN NEW."score_b" IS OLD."score_b" THEN 0 ELSE coalesce(length(CAST(NEW."score_b" AS BLOB)),0) END+CASE WHEN NEW."consistent" IS OLD."consistent" THEN 0 ELSE coalesce(length(CAST(NEW."consistent" AS BLOB)),0) END+CASE WHEN NEW."source_url" IS OLD."source_url" THEN 0 ELSE coalesce(length(CAST(NEW."source_url" AS BLOB)),0) END)) WHERE key='global';
    UPDATE sport_capacity_ledger SET accounted_bytes=accounted_bytes+(1024+4*(CASE WHEN NEW."id" IS OLD."id" THEN 0 ELSE coalesce(length(CAST(NEW."id" AS BLOB)),0) END+CASE WHEN NEW."competition_id" IS OLD."competition_id" THEN 0 ELSE coalesce(length(CAST(NEW."competition_id" AS BLOB)),0) END+CASE WHEN NEW."source" IS OLD."source" THEN 0 ELSE coalesce(length(CAST(NEW."source" AS BLOB)),0) END+CASE WHEN NEW."source_key" IS OLD."source_key" THEN 0 ELSE coalesce(length(CAST(NEW."source_key" AS BLOB)),0) END+CASE WHEN NEW."phase" IS OLD."phase" THEN 0 ELSE coalesce(length(CAST(NEW."phase" AS BLOB)),0) END+CASE WHEN NEW."round_key" IS OLD."round_key" THEN 0 ELSE coalesce(length(CAST(NEW."round_key" AS BLOB)),0) END+CASE WHEN NEW."round_label" IS OLD."round_label" THEN 0 ELSE coalesce(length(CAST(NEW."round_label" AS BLOB)),0) END+CASE WHEN NEW."team_a_name" IS OLD."team_a_name" THEN 0 ELSE coalesce(length(CAST(NEW."team_a_name" AS BLOB)),0) END+CASE WHEN NEW."team_b_name" IS OLD."team_b_name" THEN 0 ELSE coalesce(length(CAST(NEW."team_b_name" AS BLOB)),0) END+CASE WHEN NEW."team_a_ref" IS OLD."team_a_ref" THEN 0 ELSE coalesce(length(CAST(NEW."team_a_ref" AS BLOB)),0) END+CASE WHEN NEW."team_b_ref" IS OLD."team_b_ref" THEN 0 ELSE coalesce(length(CAST(NEW."team_b_ref" AS BLOB)),0) END+CASE WHEN NEW."score_a" IS OLD."score_a" THEN 0 ELSE coalesce(length(CAST(NEW."score_a" AS BLOB)),0) END+CASE WHEN NEW."score_b" IS OLD."score_b" THEN 0 ELSE coalesce(length(CAST(NEW."score_b" AS BLOB)),0) END+CASE WHEN NEW."consistent" IS OLD."consistent" THEN 0 ELSE coalesce(length(CAST(NEW."consistent" AS BLOB)),0) END+CASE WHEN NEW."source_url" IS OLD."source_url" THEN 0 ELSE coalesce(length(CAST(NEW."source_url" AS BLOB)),0) END)) WHERE key='global';
    END;
CREATE TRIGGER sport_charge_sport_team_match_delete AFTER DELETE ON sport_team_match BEGIN
    SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM sport_write_authorized) OR NOT EXISTS (
      SELECT 1 FROM sport_write_charge WHERE key='global' AND remaining_bytes>=1024
    ) THEN RAISE(ABORT, 'sport_capacity_reservation_exhausted') END;
    UPDATE sport_write_charge SET remaining_bytes=remaining_bytes-(1024) WHERE key='global';
    UPDATE sport_capacity_ledger SET accounted_bytes=accounted_bytes+(1024) WHERE key='global';
    END;
CREATE TRIGGER sport_fence_sport_relay_insert BEFORE INSERT ON sport_relay BEGIN SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM sport_write_authorized) THEN RAISE(ABORT, 'sport_write_lease_required') END; END;
CREATE TRIGGER sport_fence_sport_relay_update BEFORE UPDATE ON sport_relay BEGIN SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM sport_write_authorized) THEN RAISE(ABORT, 'sport_write_lease_required') END; END;
CREATE TRIGGER sport_fence_sport_relay_delete BEFORE DELETE ON sport_relay BEGIN SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM sport_write_authorized) THEN RAISE(ABORT, 'sport_write_lease_required') END; END;
CREATE TRIGGER sport_charge_sport_relay_insert AFTER INSERT ON sport_relay BEGIN
    SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM sport_write_authorized) OR NOT EXISTS (
      SELECT 1 FROM sport_write_charge WHERE key='global' AND remaining_bytes>=1024+4*(coalesce(length(CAST(NEW."id" AS BLOB)),0)+coalesce(length(CAST(NEW."match_id" AS BLOB)),0)+coalesce(length(CAST(NEW."relay_number" AS BLOB)),0)+coalesce(length(CAST(NEW."fencer_a_name" AS BLOB)),0)+coalesce(length(CAST(NEW."fencer_b_name" AS BLOB)),0)+coalesce(length(CAST(NEW."fencer_a_person_id" AS BLOB)),0)+coalesce(length(CAST(NEW."fencer_b_person_id" AS BLOB)),0)+coalesce(length(CAST(NEW."touches_a" AS BLOB)),0)+coalesce(length(CAST(NEW."touches_b" AS BLOB)),0)+coalesce(length(CAST(NEW."before_a" AS BLOB)),0)+coalesce(length(CAST(NEW."before_b" AS BLOB)),0)+coalesce(length(CAST(NEW."after_a" AS BLOB)),0)+coalesce(length(CAST(NEW."after_b" AS BLOB)),0)+coalesce(length(CAST(NEW."consistent" AS BLOB)),0))
    ) THEN RAISE(ABORT, 'sport_capacity_reservation_exhausted') END;
    UPDATE sport_write_charge SET remaining_bytes=remaining_bytes-(1024+4*(coalesce(length(CAST(NEW."id" AS BLOB)),0)+coalesce(length(CAST(NEW."match_id" AS BLOB)),0)+coalesce(length(CAST(NEW."relay_number" AS BLOB)),0)+coalesce(length(CAST(NEW."fencer_a_name" AS BLOB)),0)+coalesce(length(CAST(NEW."fencer_b_name" AS BLOB)),0)+coalesce(length(CAST(NEW."fencer_a_person_id" AS BLOB)),0)+coalesce(length(CAST(NEW."fencer_b_person_id" AS BLOB)),0)+coalesce(length(CAST(NEW."touches_a" AS BLOB)),0)+coalesce(length(CAST(NEW."touches_b" AS BLOB)),0)+coalesce(length(CAST(NEW."before_a" AS BLOB)),0)+coalesce(length(CAST(NEW."before_b" AS BLOB)),0)+coalesce(length(CAST(NEW."after_a" AS BLOB)),0)+coalesce(length(CAST(NEW."after_b" AS BLOB)),0)+coalesce(length(CAST(NEW."consistent" AS BLOB)),0))) WHERE key='global';
    UPDATE sport_capacity_ledger SET accounted_bytes=accounted_bytes+(1024+4*(coalesce(length(CAST(NEW."id" AS BLOB)),0)+coalesce(length(CAST(NEW."match_id" AS BLOB)),0)+coalesce(length(CAST(NEW."relay_number" AS BLOB)),0)+coalesce(length(CAST(NEW."fencer_a_name" AS BLOB)),0)+coalesce(length(CAST(NEW."fencer_b_name" AS BLOB)),0)+coalesce(length(CAST(NEW."fencer_a_person_id" AS BLOB)),0)+coalesce(length(CAST(NEW."fencer_b_person_id" AS BLOB)),0)+coalesce(length(CAST(NEW."touches_a" AS BLOB)),0)+coalesce(length(CAST(NEW."touches_b" AS BLOB)),0)+coalesce(length(CAST(NEW."before_a" AS BLOB)),0)+coalesce(length(CAST(NEW."before_b" AS BLOB)),0)+coalesce(length(CAST(NEW."after_a" AS BLOB)),0)+coalesce(length(CAST(NEW."after_b" AS BLOB)),0)+coalesce(length(CAST(NEW."consistent" AS BLOB)),0))) WHERE key='global';
    END;
CREATE TRIGGER sport_charge_sport_relay_update AFTER UPDATE ON sport_relay BEGIN
    SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM sport_write_authorized) OR NOT EXISTS (
      SELECT 1 FROM sport_write_charge WHERE key='global' AND remaining_bytes>=1024+4*(CASE WHEN NEW."id" IS OLD."id" THEN 0 ELSE coalesce(length(CAST(NEW."id" AS BLOB)),0) END+CASE WHEN NEW."match_id" IS OLD."match_id" THEN 0 ELSE coalesce(length(CAST(NEW."match_id" AS BLOB)),0) END+CASE WHEN NEW."relay_number" IS OLD."relay_number" THEN 0 ELSE coalesce(length(CAST(NEW."relay_number" AS BLOB)),0) END+CASE WHEN NEW."fencer_a_name" IS OLD."fencer_a_name" THEN 0 ELSE coalesce(length(CAST(NEW."fencer_a_name" AS BLOB)),0) END+CASE WHEN NEW."fencer_b_name" IS OLD."fencer_b_name" THEN 0 ELSE coalesce(length(CAST(NEW."fencer_b_name" AS BLOB)),0) END+CASE WHEN NEW."fencer_a_person_id" IS OLD."fencer_a_person_id" THEN 0 ELSE coalesce(length(CAST(NEW."fencer_a_person_id" AS BLOB)),0) END+CASE WHEN NEW."fencer_b_person_id" IS OLD."fencer_b_person_id" THEN 0 ELSE coalesce(length(CAST(NEW."fencer_b_person_id" AS BLOB)),0) END+CASE WHEN NEW."touches_a" IS OLD."touches_a" THEN 0 ELSE coalesce(length(CAST(NEW."touches_a" AS BLOB)),0) END+CASE WHEN NEW."touches_b" IS OLD."touches_b" THEN 0 ELSE coalesce(length(CAST(NEW."touches_b" AS BLOB)),0) END+CASE WHEN NEW."before_a" IS OLD."before_a" THEN 0 ELSE coalesce(length(CAST(NEW."before_a" AS BLOB)),0) END+CASE WHEN NEW."before_b" IS OLD."before_b" THEN 0 ELSE coalesce(length(CAST(NEW."before_b" AS BLOB)),0) END+CASE WHEN NEW."after_a" IS OLD."after_a" THEN 0 ELSE coalesce(length(CAST(NEW."after_a" AS BLOB)),0) END+CASE WHEN NEW."after_b" IS OLD."after_b" THEN 0 ELSE coalesce(length(CAST(NEW."after_b" AS BLOB)),0) END+CASE WHEN NEW."consistent" IS OLD."consistent" THEN 0 ELSE coalesce(length(CAST(NEW."consistent" AS BLOB)),0) END)
    ) THEN RAISE(ABORT, 'sport_capacity_reservation_exhausted') END;
    UPDATE sport_write_charge SET remaining_bytes=remaining_bytes-(1024+4*(CASE WHEN NEW."id" IS OLD."id" THEN 0 ELSE coalesce(length(CAST(NEW."id" AS BLOB)),0) END+CASE WHEN NEW."match_id" IS OLD."match_id" THEN 0 ELSE coalesce(length(CAST(NEW."match_id" AS BLOB)),0) END+CASE WHEN NEW."relay_number" IS OLD."relay_number" THEN 0 ELSE coalesce(length(CAST(NEW."relay_number" AS BLOB)),0) END+CASE WHEN NEW."fencer_a_name" IS OLD."fencer_a_name" THEN 0 ELSE coalesce(length(CAST(NEW."fencer_a_name" AS BLOB)),0) END+CASE WHEN NEW."fencer_b_name" IS OLD."fencer_b_name" THEN 0 ELSE coalesce(length(CAST(NEW."fencer_b_name" AS BLOB)),0) END+CASE WHEN NEW."fencer_a_person_id" IS OLD."fencer_a_person_id" THEN 0 ELSE coalesce(length(CAST(NEW."fencer_a_person_id" AS BLOB)),0) END+CASE WHEN NEW."fencer_b_person_id" IS OLD."fencer_b_person_id" THEN 0 ELSE coalesce(length(CAST(NEW."fencer_b_person_id" AS BLOB)),0) END+CASE WHEN NEW."touches_a" IS OLD."touches_a" THEN 0 ELSE coalesce(length(CAST(NEW."touches_a" AS BLOB)),0) END+CASE WHEN NEW."touches_b" IS OLD."touches_b" THEN 0 ELSE coalesce(length(CAST(NEW."touches_b" AS BLOB)),0) END+CASE WHEN NEW."before_a" IS OLD."before_a" THEN 0 ELSE coalesce(length(CAST(NEW."before_a" AS BLOB)),0) END+CASE WHEN NEW."before_b" IS OLD."before_b" THEN 0 ELSE coalesce(length(CAST(NEW."before_b" AS BLOB)),0) END+CASE WHEN NEW."after_a" IS OLD."after_a" THEN 0 ELSE coalesce(length(CAST(NEW."after_a" AS BLOB)),0) END+CASE WHEN NEW."after_b" IS OLD."after_b" THEN 0 ELSE coalesce(length(CAST(NEW."after_b" AS BLOB)),0) END+CASE WHEN NEW."consistent" IS OLD."consistent" THEN 0 ELSE coalesce(length(CAST(NEW."consistent" AS BLOB)),0) END)) WHERE key='global';
    UPDATE sport_capacity_ledger SET accounted_bytes=accounted_bytes+(1024+4*(CASE WHEN NEW."id" IS OLD."id" THEN 0 ELSE coalesce(length(CAST(NEW."id" AS BLOB)),0) END+CASE WHEN NEW."match_id" IS OLD."match_id" THEN 0 ELSE coalesce(length(CAST(NEW."match_id" AS BLOB)),0) END+CASE WHEN NEW."relay_number" IS OLD."relay_number" THEN 0 ELSE coalesce(length(CAST(NEW."relay_number" AS BLOB)),0) END+CASE WHEN NEW."fencer_a_name" IS OLD."fencer_a_name" THEN 0 ELSE coalesce(length(CAST(NEW."fencer_a_name" AS BLOB)),0) END+CASE WHEN NEW."fencer_b_name" IS OLD."fencer_b_name" THEN 0 ELSE coalesce(length(CAST(NEW."fencer_b_name" AS BLOB)),0) END+CASE WHEN NEW."fencer_a_person_id" IS OLD."fencer_a_person_id" THEN 0 ELSE coalesce(length(CAST(NEW."fencer_a_person_id" AS BLOB)),0) END+CASE WHEN NEW."fencer_b_person_id" IS OLD."fencer_b_person_id" THEN 0 ELSE coalesce(length(CAST(NEW."fencer_b_person_id" AS BLOB)),0) END+CASE WHEN NEW."touches_a" IS OLD."touches_a" THEN 0 ELSE coalesce(length(CAST(NEW."touches_a" AS BLOB)),0) END+CASE WHEN NEW."touches_b" IS OLD."touches_b" THEN 0 ELSE coalesce(length(CAST(NEW."touches_b" AS BLOB)),0) END+CASE WHEN NEW."before_a" IS OLD."before_a" THEN 0 ELSE coalesce(length(CAST(NEW."before_a" AS BLOB)),0) END+CASE WHEN NEW."before_b" IS OLD."before_b" THEN 0 ELSE coalesce(length(CAST(NEW."before_b" AS BLOB)),0) END+CASE WHEN NEW."after_a" IS OLD."after_a" THEN 0 ELSE coalesce(length(CAST(NEW."after_a" AS BLOB)),0) END+CASE WHEN NEW."after_b" IS OLD."after_b" THEN 0 ELSE coalesce(length(CAST(NEW."after_b" AS BLOB)),0) END+CASE WHEN NEW."consistent" IS OLD."consistent" THEN 0 ELSE coalesce(length(CAST(NEW."consistent" AS BLOB)),0) END)) WHERE key='global';
    END;
CREATE TRIGGER sport_charge_sport_relay_delete AFTER DELETE ON sport_relay BEGIN
    SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM sport_write_authorized) OR NOT EXISTS (
      SELECT 1 FROM sport_write_charge WHERE key='global' AND remaining_bytes>=1024
    ) THEN RAISE(ABORT, 'sport_capacity_reservation_exhausted') END;
    UPDATE sport_write_charge SET remaining_bytes=remaining_bytes-(1024) WHERE key='global';
    UPDATE sport_capacity_ledger SET accounted_bytes=accounted_bytes+(1024) WHERE key='global';
    END;
