import { sql } from 'drizzle-orm';
import { customType, text } from 'drizzle-orm/sqlite-core';

/** Database-clock milliseconds, including the fractional second. */
export const nowMilliseconds = sql`(cast(strftime('%s', 'now') as integer) * 1000 + cast(substr(strftime('%f', 'now'), 4, 3) as integer))`;

/** UUID v4 generated by SQLite, so raw imports and Drizzle share the default. */
export const uuidV4 = sql`(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', (random() & 3) + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6))))`;

/** Unlike SQLite's timestamp mode in seconds, the application retains Date. */
export const timestampMilliseconds = customType<{ data: Date; driverData: number }>({
  dataType: () => 'integer',
  toDriver(value) {
    const milliseconds = value.getTime();
    if (!Number.isSafeInteger(milliseconds)) throw new TypeError('Invalid D1 timestamp.');
    return milliseconds;
  },
  fromDriver(value) {
    const date = new Date(value);
    if (!Number.isSafeInteger(value) || !Number.isFinite(date.getTime())) {
      throw new TypeError('Invalid stored D1 timestamp.');
    }
    return date;
  },
});

/** Decimal TEXT deliberately avoids SQLite NUMERIC affinity and float rounding. */
export const decimalText = customType<{ data: string; driverData: string }>({
  dataType: () => 'text',
  toDriver: (value) => value,
  fromDriver: (value) => value,
});

/** JSON TEXT, not a PostgreSQL array literal or a lossy comma-separated list. */
export function jsonText<T = unknown>(name: string) {
  return customType<{ data: T; driverData: string }>({
    dataType: () => 'text',
    toDriver(value) {
      const encoded = JSON.stringify(value);
      if (encoded === undefined) throw new TypeError('D1 JSON cannot encode undefined.');
      return encoded;
    },
    fromDriver: (value) => JSON.parse(value) as T,
  })(name);
}

/** Keep the enumValues API used by domain code without importing pg-core. */
export function sqliteEnum<const Values extends readonly [string, ...string[]]>(
  enumName: string,
  enumValues: Values,
) {
  return Object.assign(
    (name: string) => text(name, { enum: enumValues }),
    { enumName, enumValues },
  );
}
