/** Deterministic local SQL generation only. Never opens a database or loads dotenv. */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import {
  CAPACITY_DEFINITIONS, CAPACITY_MAX_BUDGET_BYTES, rowChargeDefinition,
} from '../src/lib/ingest/sport-incremental/capacity';
import { FENCED_TABLES } from '../src/lib/ingest/sport-incremental/schema';

// SQL0002 is already applied in production with the 4 GiB ceiling and must stay
// byte-identical to what was applied; SQL0005 moves it to the current ceiling.
const HISTORIC_BUDGET_BYTES = 4 * 1024 ** 3;
const currentCeiling = `budget_bytes<=${CAPACITY_MAX_BUDGET_BYTES})`;
if (!CAPACITY_DEFINITIONS.sport_write_context.includes(currentCeiling)) throw new Error('sport_sql_generator_budget');
const historicDefinitions: Record<string, string> = {
  ...CAPACITY_DEFINITIONS,
  sport_write_context: CAPACITY_DEFINITIONS.sport_write_context
    .replace(currentCeiling, `budget_bytes<=${HISTORIC_BUDGET_BYTES})`),
};

const header = [
  '-- Apply AFTER 0000/0001 and complete verified import, with old sport writers stopped.',
  '-- Generated by scripts/generar-guardia-deportiva.ts; verify with --comprobar.',
  '-- D1 physical storage uses meta.size_after, never denied page PRAGMAs.',
  '-- Ledger charges committed row mutations and batch overhead, never unused projections.',
  '-- Updates charge every touched row and full changed-column bytes, not retained payloads.',
  '-- Monotonic conservative policy accounting, NOT a physical/account spending theorem.',
  'ALTER TABLE sport_write_lease ADD COLUMN lease_version INTEGER NOT NULL DEFAULT 1 CHECK (lease_version > 0);',
];
const definitions = Object.values(historicDefinitions).flatMap((definition, i) =>
  i === 0 ? [definition, "INSERT INTO sport_capacity_ledger(key,accounted_bytes,blocked) VALUES('global',0,0)"] : [definition]);
const fences = FENCED_TABLES.flatMap((table) => ['insert', 'update', 'delete'].map((action) =>
  `CREATE TRIGGER sport_fence_${table}_${action} BEFORE ${action.toUpperCase()} ON ${table} BEGIN SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM sport_write_authorized) THEN RAISE(ABORT, 'sport_write_lease_required') END; END`));
const charges = FENCED_TABLES.flatMap((table) => ['insert', 'update', 'delete'].map((action) => rowChargeDefinition(table, action)));
const sql0002 = `${header.join('\n')}\n${[...definitions, ...fences, ...charges].map((text) => `${text};`).join('\n')}\n`;

// DROP TABLE removes the context's own triggers; triggers on other tables that
// mention the view or the context resolve their names at execution time, so they
// stay valid. ALTER TABLE RENAME would re-validate them against a missing view.
const rebuilt = ['sport_write_context', 'sport_write_authorized', 'sport_context_claim',
  'sport_context_reserve', 'sport_context_close', 'sport_context_immutable'] as const;
const header0005 = [
  `-- Raises the sport_write_context budget ceiling to ${CAPACITY_MAX_BUDGET_BYTES} bytes (8 GiB).`,
  '-- Application allocation, NOT a spending cap; D1 allows up to 10 GB per database on the paid plan.',
  '-- Generated by scripts/generar-guardia-deportiva.ts; verify with --comprobar.',
  '-- Rebuilds only sport_write_context, sport_write_authorized and the sport_context_* triggers.',
  '-- sport_capacity_ledger and every other guard are untouched. Fails (CHECK constraint)',
  '-- and rolls back unless no write context or charge is open.',
];
const statements0005 = [
  'CREATE TABLE _guardia_0005 (abiertos INTEGER NOT NULL CHECK (abiertos = 0))',
  'INSERT INTO _guardia_0005(abiertos) SELECT (SELECT count(*) FROM sport_write_context)+(SELECT count(*) FROM sport_write_charge)',
  'DROP TABLE _guardia_0005',
  'DROP VIEW sport_write_authorized',
  'DROP TABLE sport_write_context',
  ...rebuilt.map((name) => CAPACITY_DEFINITIONS[name]),
];
const sql0005 = `${header0005.join('\n')}\n${statements0005.map((text) => `${text};`).join('\n')}\n`;

const files = [
  { file: fileURLToPath(new URL('../drizzle-d1/0002_guardia_deportiva.sql', import.meta.url)), sql: sql0002 },
  { file: fileURLToPath(new URL('../drizzle-d1/0005_presupuesto_8gib.sql', import.meta.url)), sql: sql0005 },
];
try {
  const args = process.argv.slice(2);
  if (args.length !== 1 || !['--comprobar', '--escribir'].includes(args[0])) throw new Error('sport_sql_generator_arguments');
  for (const { file, sql } of files) {
    if (args[0] === '--escribir') await writeFile(file, sql, 'utf8');
    else if (await readFile(file, 'utf8') !== sql) throw new Error('sport_sql_generated_mismatch');
  }
  console.log(JSON.stringify({ guardiaGenerada: true, modo: args[0] }));
} catch {
  console.error('sport_sql_generator_failed'); process.exitCode = 1;
}
