/** Deterministic local SQL generation only. Never opens a database or loads dotenv. */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { CAPACITY_DEFINITIONS, rowChargeDefinition } from '../src/lib/ingest/sport-incremental/capacity';
import { FENCED_TABLES } from '../src/lib/ingest/sport-incremental/schema';

const header = [
  '-- Apply AFTER 0000/0001 and complete verified import, with old sport writers stopped.',
  '-- Generated by scripts/generar-guardia-deportiva.ts; verify with --comprobar.',
  '-- D1 physical storage uses meta.size_after, never denied page PRAGMAs.',
  '-- Ledger charges committed row mutations and batch overhead, never unused projections.',
  '-- Updates charge every touched row and full changed-column bytes, not retained payloads.',
  '-- Monotonic conservative policy accounting, NOT a physical/account spending theorem.',
  'ALTER TABLE sport_write_lease ADD COLUMN lease_version INTEGER NOT NULL DEFAULT 1 CHECK (lease_version > 0);',
];
const definitions = Object.values(CAPACITY_DEFINITIONS).flatMap((definition, i) =>
  i === 0 ? [definition, "INSERT INTO sport_capacity_ledger(key,accounted_bytes,blocked) VALUES('global',0,0)"] : [definition]);
const fences = FENCED_TABLES.flatMap((table) => ['insert', 'update', 'delete'].map((action) =>
  `CREATE TRIGGER sport_fence_${table}_${action} BEFORE ${action.toUpperCase()} ON ${table} BEGIN SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM sport_write_authorized) THEN RAISE(ABORT, 'sport_write_lease_required') END; END`));
const charges = FENCED_TABLES.flatMap((table) => ['insert', 'update', 'delete'].map((action) => rowChargeDefinition(table, action)));
const sql = `${header.join('\n')}\n${[...definitions, ...fences, ...charges].map((text) => `${text};`).join('\n')}\n`;
const file = fileURLToPath(new URL('../drizzle-d1/0002_guardia_deportiva.sql', import.meta.url));
try {
  const args = process.argv.slice(2);
  if (args.length !== 1 || !['--comprobar', '--escribir'].includes(args[0])) throw new Error('sport_sql_generator_arguments');
  if (args[0] === '--escribir') await writeFile(file, sql, 'utf8');
  else if (await readFile(file, 'utf8') !== sql) throw new Error('sport_sql_generated_mismatch');
  console.log(JSON.stringify({ guardiaGenerada: true, modo: args[0] }));
} catch {
  console.error('sport_sql_generator_failed'); process.exitCode = 1;
}
